.buildkite/pipeline.yml
.cspell.json
.github/workflows/lint.yml

Moves lint step back to GitHub Actions so that we can use known version (12) of clang-format.
This reverts commit 94878424568b661ecd007f5c5284ac2113bc9104.

Move lint step back to GH Actions

---

Makefile
Plugins/Bugsnag/Source/Bugsnag/Private/Apple/ApplePlatformBugsnag.cpp
Plugins/Bugsnag/Source/Bugsnag/Private/BugsnagFunctionLibrary.cpp

Now that Bugsnag functionality is enabled for macOS, opening a project in Unreal Editor will also start Bugsnag in that process.
The aim of this PR is to avoid sending spurious errors and sessions.
1. Ignores crashes that occur in the Editor outside of a PIE session, to avoid sending non-game related crashes to the dashboard. This records the state of `GIsPlayInEditorWorld` at crash time to determine whether the game was being played. Note that crashes that were caused by game code but occurred after play ended (e.g. if there some delay before the crash happening) will be ignored.
2. Disables automatic session tracking in the Editor, to avoid skewing session stability scores.
3. Disables app hang detection in the Editor, since any hangs are likely to be caused by the Editor whose UI …

[PLAT-7903] Improve in-Editor behaviour

---

Plugins/Bugsnag/Source/Bugsnag/Private/Android/AndroidPlatformConfiguration.cpp
Plugins/Bugsnag/Source/Bugsnag/Private/BugsnagConfiguration.cpp
Plugins/Bugsnag/Source/Bugsnag/Public/BugsnagConfiguration.h
Plugins/Bugsnag/Source/Bugsnag/Public/BugsnagSettings.h

`bugsnag-cocoa`'s automatic release stage detection is based on the `DEBUG` compiler macro. This does not work for Unreal Engine games because we always prebuild `bugsnag-cocoa` in release mode, so the release stage was always being reported as `"production"`.
`FBugsnagConfiguration` now controls the automatic release stage, setting it to production for Shipping builds.
Tested manually to ensure `"development"` is sent for non-shipping builds.
E2E scenarios verify that `"production"` is sent by default (the fixture is built Shipping configuration) and that manually specifying a release stage overrides this.

[PLAT-7957] Fix reported release stage for iOS & Mac

---

.buildkite/pipeline.yml

Migrate the 4.26 and 4.27 steps to the ms-arm-12 build queue.
Change the queue for the 4.26 and 4.27 steps to run on the new macos 12 build queue
Full CI test run

Move unreal 4.27 and 4.26 steps to Macos12 

---

.buildkite/pipeline.yml

Move the Unreal Engine 4.23/4.25/5.0EA steps to the new macos 10.15 queue
Move the Unreal Engine 4.23/4.25/5.0EA steps to the new macos 10.15 queue
Full CI run [here](https://buildkite.com/bugsnag/bugsnag-unreal/builds/753)

Move the UE 4.23/4.25/5.0EA steps to a new build queue

---

CHANGELOG.md
Plugins/Bugsnag/Source/Bugsnag/Private/Android/AndroidPlatformConfiguration.cpp
Plugins/Bugsnag/Source/Bugsnag/Private/Android/JNIUtilities.cpp
Plugins/Bugsnag/Source/Bugsnag/Private/Android/JNIUtilities.h
Plugins/Bugsnag/Source/Bugsnag/Public/BugsnagConfiguration.h
features/fixtures/generic/Source/TestFixture/Scenarios/NotifyScenario.cpp
features/handled_errors.feature

Make the `MaxReportedThreads` property available for configuration.
Adds `GetMaxReportedThreads()` and `SetMaxReportedThreads()` and passes the value on to the Android notifier when starting.
Amends existing scenario to verify thread limit takes effect.

[PLAT-8190] Add Config.MaxReportedThreads

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Move the Android build steps off of the ARM machines to reduce the flakeyness of those steps.
Covered by a Full CI

Move Android build step off of ARM machines

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Move the Android test fixture build back to ARM now that the JDK is stable.
- Default pipeline to use the `macos-12-arm` queue
- Bump the XCode version so it runs on macOS 12.
Covered by a full CI run.

Move Android fixture build to ARM

---

Makefile

Makes `editor` and `run` Makefile targets work with UE 5

Add UE 5.0 support to Makefile

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml

Pin all Xcode13 builds to a specific version, avoiding the use of symlinks.
We've had very slow/unreliable builds when targeting the XCode 13 symlink (which has just change from 13.2.1 to 13.4 on the build servers).  
Covered by a full CI run.

Pin all Xcode13 builds

---

CHANGELOG.md
Plugins/Bugsnag/Source/Bugsnag/Bugsnag_UPL.xml
deps/bugsnag-plugin-android-unreal/build.gradle

Bump bugsnag-android dependency to v5.23.0
Note - this includes a new configuration option that needs to be added to the Unity codebase.
* Added configuration option to control whether internal errors are sent to Bugsnag
[#1701](https://github.com/bugsnag/bugsnag-android/pull/1701)
* Fixed Bugsnag interactions with the Google ANR handler on newer versions of Android
[#1699](https://github.com/bugsnag/bugsnag-android/pull/1699)
* Overwriting & clearing event metadata in the NDK plugin will no longer leave phantom values
[#1700](https://github.com/bugsnag/bugsnag-android/pull/1700)

Bump bugsnag-android to v5.23.0

---

CHANGELOG.md
Plugins/Bugsnag/Source/Bugsnag/Bugsnag_UPL.xml
deps/bugsnag-plugin-android-unreal/build.gradle
deps/bugsnag-plugin-android-unreal/src/main/java/com/bugsnag/android/unreal/UnrealPlugin.java

Remove the `discardClasses` workaround on Android, now that the underlying bug has been fixed:
* https://github.com/bugsnag/bugsnag-android/pull/1710
Removes workaround code from `UnrealPlugin`.
Imports were "optimized" by Android Studio.
Verified by existing E2E tests on CI.

[PLAT-8642] Remove Android `discardClasses` workaround

---

Plugins/Bugsnag/Source/Bugsnag/Private/Apple/AppleBugsnagUtils.h

Fix an uncaught exception observed when running unit tests.
Checks `+[NSJSONSerialization isValidJSONObject:]` before calling `+[NSJSONSerialization dataWithJSONObject:options:error:]`, preventing an exception if `Dictionary` is not valid JSON.
Verified fix by running unit tests.

Fix exception in FJsonObjectFromNSDictionary

---

.buildkite/pipeline.yml

Update the Windows steps to use the new Windows CI machines
Change the Windows queue to the new machine group
Covered by full CI

Move Unreal pipeline over to new CI machines

---

Plugins/Bugsnag/Source/Bugsnag/Private/Apple/ApplePlatformBugsnag.cpp

Remove use of `-[BugsnagMetadata deepCopy]` method which is [being removed](https://github.com/bugsnag/bugsnag-cocoa/pull/1444).
Uses `copy` instead of `deepCopy`.
Verified no observable changes via existing tests.

Use `-[BugsnagMetadata copy]` instead of `-deepCopy`

---

Gemfile
Gemfile.lock
features/steps/unreal_steps.rb
features/support/env.rb

Fix a flake [observed](https://buildkite.com/bugsnag/bugsnag-unreal/builds/1235#018238eb-75ba-45c4-a7e0-9228dcdbcf35) in overnight run.
Uses `Maze.config.captured_invalid_requests` to ignore invalid session payloads received during crashing scenarios. If the fixture crashes while a session has been partially transmitted, this would otherwise cause the failure linked to above.
Verified on CI

Ignore invalid sessions from crashing scenarios

---

Plugins/Bugsnag/Source/Bugsnag/Private/BugsnagFunctionLibrary.cpp
Source/BugsnagExampleEditor.Target.cs

`UBugsnagFunctionLibrary::Notify` would crash if `CaptureStackBackTrace` returned a trace size small enough to cause unsigned underflow when adjusting the stack size to eliminate boilerplate entries.
This PR:
* Casts the actually signed value that `CaptureStackBackTrace` returns back to a signed type.
* Makes sure that an invalid `Depth` can never cause a crash.
Manually tested on the example app.

[PLAT-9257] Bugfix for unsigned arithmetic underflow

---

.buildkite/pipeline.yml
features/scripts/build-plugin-wsl.sh

Add  Unreal engine 5.1 to  to windows CI machines
Add steps for UE 5.1 to the windows CI machine
Covered by CI

Add Unreal Engine 5.1 to Windows CI machines

---

Plugins/Bugsnag/Source/Bugsnag/Private/BugsnagFunctionLibrary.cpp
features/fixtures/generic/Source/TestFixture/ScenarioNames.h
features/fixtures/generic/Source/TestFixture/Scenarios/NotifyMultithreadedScenario.cpp
features/handled_errors.feature

Unreal's CaptureStackBackTrace implementation for Android has a path that is not thread-safe. Add a mutex to ensure only one thread can call it at a time.
Tested manually using multiple threads. Before the fix, it crashes pretty consistently.

[PLAT-9258] Compensate for lack of thread safety in Unreal's Android CaptureStackBackTrace

---

features/fixtures/generic/Plugins/Tweaks/Source/Tweaks/Tweaks_UPL.xml

Set the compile SDK version for the android test fixture to the supported version. This only affects the test fixture.
Covered by full CI

Set Android compile SDK version for test fixture

---

CHANGELOG.md
Plugins/Bugsnag/Source/Bugsnag/Private/BugsnagConfiguration.cpp
Plugins/Bugsnag/Source/Bugsnag/Public/BugsnagSettings.h

In the v5.28.0 of the android notifier we upped the max breadcrumbs to 500. The unreal notifier was bumped to use this dependency in v1.5.1. With this android update we should allow for a max of 500 breadcrumbs on events in unreal
maxbreadcrumbs clamp was upped from 100 - 500
Set plugin breadcrumbs value to 500 in the editor and then sent 500 breadcrumbs in an event to the dashboard. all breadcrumbs correctly set in dashboard

Updated breadcrumb clamp

---

.buildkite/pipeline.full.yml
.buildkite/pipeline.yml
.buildkite/unreal.5.3.yml

Guard against future removal of Appium 1 from device farms.
Covered by a full CI run.

Do not pin Appium version without reason

---

Gemfile
Gemfile.lock

Bump the version of Maze Runner to 8.13.X to fix the following error.
`Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'`
Covered by CI

Bump the version of Maze Runner to fix CI issues
